### ISSUE TITLE
Missing AJP Connector b/c of commit "add jmxmp listener"

### ISSUE THREAD

**Issue by sepe81** [podbox/docker-tomcat8#1]
Because of [commit 7aec812](https://github.com/podbox/docker-tomcat8/commit/7aec812276f743ea3d6c13469c9a1d2c994d2ac0) and the newly added server.xml there are several implict changes in tomcat configuration.

It's good to see the UTF-8 encoding for `<Connector port="8080" protocol="HTTP/1.1" URIEncoding="UTF-8" ... />`. 

However, in the default tomcat config there exists `<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />`. This has been removed for the current docker image. Could we please reintegrate AJP with UTF-8 support?

**Comment by glivron** [comment]
We prefer to keep the configuration as simple as possible.
You can inherit from this container and change the configuration as your needs.
